[package]
name                   = "kryvora-db"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true
description            = "SQLite persistence, migrations, and repositories for KRYVORA."

[lints]
workspace = true

[dependencies]
kryvora-core = { workspace = true }
rusqlite     = { workspace = true }
thiserror    = { workspace = true }
time         = { workspace = true }
sha2         = { workspace = true }
hex          = { workspace = true }
serde        = { workspace = true }
uuid         = { workspace = true }

[dev-dependencies]
rusqlite = { workspace = true }
tempfile = "3"
serde_json = { workspace = true }